### ISSUE TITLE
Error while Vagrant Up command in standalone and multinode setup

### ISSUE THREAD

**Issue by Roshan4u** [everpeace/vagrant-mesos#65]
![er](https://cloud.githubusercontent.com/assets/10377772/7907078/2e9250b2-0852-11e5-9a82-859d49519837.jpg)
while running following command on terminal
$ git clone https://github.com/everpeace/vagrant-mesos.git (work fine)
$ cd vagrant-mesos/standalone (work fine)
$ vagrant up 
when i put vagrant up its shows error for VboxManage missing

Steps i have done: installed oracle virtual box compatible version and then putty
connected to it by given configuration 
127.0.0.1:2222
uid & password: vagrant 
 So how to run vagrant up

path for virtual box is set in windows env :C:\Program Files\Oracle\VirtualBox

**Comment by everpeace** [comment]
You DID try to `vagrant up` vagrant-mesos in virtual machine, didn't you?
I think it is obvious that vagrant output there are no VirtualBox because your vm doesn't have virtualbox in it.  

If you intalled virtualbox software in your vm, vagrant-mesos will work fine.
Or, if you `vagrant up` vagrant-mesos in your host machine(windows machine) by using cygwin or something, it will work fine maybe.

Thanks,

**Comment by everpeace** [comment]
@Roshan4u  Do you still have this problem??  Would you mind closing this issue?

**Comment by everpeace** [comment]
If you still had the issue, please feel free to reopen it.
