### ISSUE TITLE
No master is currently leading ...

### ISSUE THREAD

**Issue by ilackarms** [everpeace/vagrant-mesos#79]
When I run `vagrant up` inside the multinode directory, the cluster seems to boot up without issue. However the "No master is currently leading ..." message never goes away (or at least takes a long time), and neither master ever detects any of the slaves. Could this be a problem with zookeeper?  I have tried reducing the number of Masters to 1, as well as the number of slaves to 1, but the master still seems to not detect the slave.

**Comment by schmidtjohannes** [comment]
i had to set up a basic config file in /etc/zookeeper/conf/zoo.cfg with
tickTime=2000
dataDir=/var/lib/zookeeper
clientPort=2181
After that a restart of the cluster will help
I had to start marathon manually
/opt/marathon/bin/start --master zk://172.31.0.11:2181/mesos --zk zk://172.31.0.11:2181/marathon --http_port 8080
But I got the impression that something is not working with chef, because there are some config templates for zk in this project.

**Comment by ilackarms** [comment]
This issue was caused by specifying a synced folder in the vagrantfile
